
COLORS = {
    'menu': '#333333',
    'note.normal': 'white',
    'note.highlight': '#blue',
    'note.selected': 'pink',
    'fingerstates.pressed': '#AA4455',
    'fingerstates.released': '#ABABAB',
    'slider.normal': '#343434',
    'slider.highlight': '#blue',
    'slider.pressed': '#AA4455',
    'graph.background': '#041022',
    'graph.grid': '#04183d',
    'graph.row.plus.highlight': '#243756',
    'graph.row.plus.normal': '#637b84',
    'graph.row.background.highlight': '#242a35',
    'graph.row.background.normal': '#1c2638',
    'graph.connection.dead': '#252525',
    'graph.connection.min': '#336622',
    'graph.connection.max': '#EECC44',
    'graph.connection.highlight': '#FF9900',
    'graph.index.background.dead': '#252525',
    'graph.index.background.min': '#253012',
    'graph.index.background.max': '#888800',
    'graph.index.border.highlight': '#4499EE',
    'graph.index.border.normal': '#black',
    'graph.index.border.selected': '#dfdfdf',
    'graph.index.item.border.selected': '#4499EE'}