
COLORS = {
    'menu': '#333333',
    'note.normal': 'white',
    'note.highlight': '#blue',
    'note.selected': 'pink',
    'fingerstates.pressed': '#AA4455',
    'fingerstates.released': '#ABABAB',
    'balloon.closer.hover': '#d0a895',
    'balloon.closer.free': "#B3B3B3",
    'balloon.closer.cross': "#4b4b4b",
    'balloon.border': '#4b4b4b',
    'balloon.title': '#4b4b4b',
    'balloon.background': '#111111',
    'balloon.text': '#6E6E6E',
    'slider.normal': '#343434',
    'slider.highlight': '#blue',
    'slider.pressed': '#AA4455',
    'graph.background': '#BBBBBB',
    'graph.grid':  '#CDCDCD',
    'graph.row.plus.highlight': '#BABABA',
    'graph.row.plus.normal': 'black',
    'graph.row.background.highlight': '#BABABA',
    'graph.row.background.normal': '#9A9A9A'}